# Generated by Django 5.2.3 on 2025-07-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_kit_remove_itempanier_panier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=100)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kit')),
            ],
        ),
    ]
