# Generated by Django 5.2.3 on 2025-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itempanier',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='itempanier',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='ItemPanier',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
